---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pavan
spec:
  replicas: 2
  selector:
    matchLabels:
      env: green
  template:
    metadata:
      name: mytemplate
      labels:
        env: green
    spec:
      containers:
        - name: cont2
          image: kumar49/pavankumar:game
          ports:
            - containerPort: 80
